version: "2"
services:
  php-apache:
    image: 2532/powerrot:test
    ports:
      - "8003:80"
    volumes:
      - ./public_html:/var/www/html

  mysql:
    image: mysql:5.7.24
    restart: always
    ports:
      - "3310:3306"
    environment:
      MYSQL_DATABASE: "contact"
      MYSQL_USER: "root"
      MYSQL_ROOT_PASSWORD: "some_password"
    volumes:
      - ./contact.sql:/docker-entrypoint-initdb.d/contact.sql
      - ./mysql_8_conf.d:/etc/mysql/conf.d
